
version: "3.9"
services:
  db:
    image: postgres:16
    container_name: desafio_postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-desafio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-desafio123}
      POSTGRES_DB: ${POSTGRES_DB:-desafio_db}
      TZ: America/Sao_Paulo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4:8.11
  #   container_name: desafio_pgadmin
  #   restart: unless-stopped
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
  #     TZ: America/Sao_Paulo
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  pgdata:
